#!/usr/bin/env bash
# print best school 10 times
n=1
while (( "$n" <= 20 ))
do
	case $n in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		echo "$n"
	esac
	((n++))
done
