#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
n=0
m=1
while [ $n -le 12 ]
do
    echo "Hour: $n"
    while [ $m -le 59 ]
    do
        echo "$m"
        ((m++))
    done
    m=1
    ((n++))
done